url: "https://nupublicspeaking.github.io"
baseurl: ""

# Site settings
title: NU Public Speaking Club
email: sunmch15@gmail.com
description: "The Public Speaking Club for Northwestern University."


# Team names, titles and social links
people:
- name: Mike (HongYoul) Park
  pic: 1-small
  position: President
  identity: PhD Student in Material Science
  email: hongpark2023@u.northwestern.edu
  
- name: Ethan (Jinpu) Yang
  pic: 2-small
  position: Vice President of Education
  identity: PhD Student in Finance
  email:

- name: Muchen Sun
  pic: 3-small
  position: Vice President of Public Relations & Webmaster
  identity: MS Student in Mechanical Engineering
  email: muchensun2021@u.northwestern.edu

- name: Suman Bhandari
  pic: 4-small
  position: Treasurer
  identity: PhD Student in Mechanical Engineering
  email: sumanbhandari2022@u.northwestern.edu

- name: Anastasiia Tsarenko
  pic: 5-small
  position: External Advisor
  identity: Founder of Perform On Top
  email:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)

# Postal address (add as many lines as necessary)

# Build settings
markdown: kramdown
permalink: pretty