url: "https://nupublicspeaking.github.io"
baseurl: ""

# Site settings
title: NU Public Speaking Club
email: sunmch15@gmail.com
description: "The Public Speaking Club for Northwestern University."


# Team names, titles and social links
people:
- name: Muchen Sun
  pic: 3-small
  position: President
  identity: PhD Student in Mechanical Engineering
  email: muchen@u.northwestern.edu

- name: Mike (HongYoul) Park
  pic: 1-small
  position: Vice President of Education
  identity: PhD Student in Material Science
  email: hongpark2023@u.northwestern.edu
  
- name: Metehan Çam
  pic: 2-small
  position: Vice President of Membership
  identity: PhD Student in Mechanical Engineering
  email: metehancam2023@u.northwestern.edu

- name: Gabrielle Guillerm
  pic: 4-small
  position: Vice President of Public Relations
  identity: PhD Student in History
  email: gabrielleguillerm2019@u.northwestern.edu

- name: Giovanni Sciacovelli
  pic: 5-small
  position: Vice President of Finance & Treasurer
  identity: PhD Student in Economics
  email: giovannisciacovelli2024@u.northwestern.edu 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)

# Postal address (add as many lines as necessary)

# Build settings
markdown: kramdown
permalink: pretty